Add support for MPS
OpenImageDenoise/oidn pull request #138
Opened 2022-06-24 17:33 UTC by Developer-Ecosystem-Engineering

We've added support for OIDN_MPS on configurations where MPS is available. This results in at least a 10x performance improvement over CPU only

- Added odinTests for MPS
- Updated cmake file to detect and use MPS when available
- Added MPSGraphNetwork & MPS Devices

### Test Results

On a 2.6 GHz 6-Core Intel Core i7 with AMD Radeon Pro 5600M

- CPU
  - Benchmarking: ntimes=20 sec=45.4701, msec/image=2273.51

- MPS
  - Benchmarking: ntimes=20 sec=2.91587, msec/image=145.794

RT.hdr_alb_nrm.1920x1080 ... 1058.66 (145.004) msec/image
RT.ldr_alb_nrm.1920x1080 ... 1086.15 (144.358) msec/image
RT.hdr_alb_nrm.3840x2160 ... 4518.11 (614.316) msec/image
RT.ldr_alb_nrm.3840x2160 ... 4495.98 (608.582) msec/image
RT.hdr_alb_nrm.1280x720 ... 468.137 (66.82) msec/image
RT.ldr_alb_nrm.1280x720 ... 470.525 (65.8203) msec/image
RTLightmap.hdr.2048x2048 ... 2045.76 (234.115) msec/image
RTLightmap.hdr.4096x4096 ... 9731.88 (1021.19) msec/image
RTLightmap.hdr.1024x1024 ... 544.029 (58.3557) msec/image

2023-03-18 08:36 UTC, abebeos commented
a "pixel-perfect" PR.

@atafra, why is this not even getting a comment?

2023-03-18 12:18 UTC, abebeos commented
> a "pixel-perfect" PR.

@Developer-Ecosystem-Engineering , while the speedtests impress, having all changes within one commit makes the review difficult.

I would split this down into multiple commits.

2023-03-18 12:24 UTC, atafra commented
@abebeos This will be available in the upcoming Open Image Denoise 2.0.

2023-03-18 12:26 UTC, abebeos requested changes
Replay this pr

-less general changes
-more commits
-more comments

2023-03-18 12:26 UTC, abebeos commented on .gitmodules
> +url=https://github.com/OpenImageDenoise/mkl-dnn.gitOpenImageDenoise/mkl-dnn.git
You should not changes existent build behavior. Here you break the fork behavior.

2023-03-18 12:26 UTC, abebeos commented on CMakeLists.txt
> +
* Change of behavior.
* undocumented.

2023-03-18 12:26 UTC, abebeos commented on apps/oidnTest.cpp
> +
Aborting review. Too many undocumented general changes (outside of a #if defined(OIDN_MPS))

2023-03-18 12:28 UTC, abebeos commented
> @abebeos This will be available in the upcoming Open Image Denoise 2.0.

Nice. Where can one follow the development? And do you have an estimated release date?

2023-03-18 12:30 UTC, atafra commented
The development for 2.0 is currently internal. It is planned to be released in about a month.

2023-06-22 22:13 UTC, closed without merging

2023-11-20 15:34 UTC, atafra commented
Not yet but it will be released very soon now.